### ISSUE TITLE
turn on inspector for *nix binaries

### ISSUE THREAD

**Issue by sramam** [vercel/pkg-fetch#107]
[It seems](https://github.com/vercel/pkg-fetch/blob/9f13288449ac8d44841cf9dfed39233ed87af169/lib/build.js#L73) the inspector is turned off for *nix builds. I can't see an explicit reason for this in the commit history. Interestingly, this is not done for windows builds.

Wondering if it can be turned back on? Or can any light be shed on reason for this limitation?

**Comment by jesec** [comment]
Users do not like end-users to inspect.

**Comment by sramam** [comment]
I understand. But this force sets an option, only on a single OS. 
I was using it to inspect the binary in development (to figure some cross OS bug) and this made it impossible.

Hopefully you'll reconsider and use one of the options mentioned:
1. Document recommended behavior (requires use of `--without-inspector`)
2. Invert the behavior of the flag (`--use-inspector`)

Making this behavior controllable from the CLI without having to compile from source would be a huge
convenience in the few number of cases that it is needed. Getting to the the corner case where one needs this is hard enough. Current implementation makes it impossible to surmount the problem.
