### ISSUE TITLE
How to build uploaded-v2.6-node-v10.17.0-win-64

### ISSUE THREAD

**Issue by 3DGISKing** [vercel/pkg-fetch#108]
Hi, 
Thank you for this great project.
I need to build the binary based on Node js 10.17.0 from scratch on Windows 64.
Actually, I want to build and get the result the same as uploaded-v2.6-node-v10.17.0-win-86 from the source.
But the result was different from the uploaded-v2.6-node-v10.17.0-win-86.
They are different from raw size.

What I tried
1 Install pkg-fetch 2.6.4
2 install Python 2.7.17
3 install NASM 2.13
4 install Visual Studio 2017 Community
5 manually get Node js 10.17.0 source (I used the source cloned by pkg-fetch 2.6.4 's build step )
6 manually apply patch : node.v10.17.0.cpp.patch from pkg-fetch 2.6.4 source.
7 build
   I used the same command as pkg-fetch 2.6.4 for the build.
   **“cmd /c vcbuild.bat x64 noetw nosign noperfctr”**

But the result was different from the uploaded-v2.6-node-v10.17.0-win-64

![image](https://user-images.githubusercontent.com/26606704/98238045-c8dbab80-1fa0-11eb-9644-edfb63be4cfc.png)

   How to build binary same as uploaded-v2.6-node-v10.17.0-win-64 from source?
   Any tip would be appreciated.

**Comment by kwisatz** [comment]
In general, I think that detailing the build process in the docs would be a good idea. I understand that `pkg-fetch` doesn't want to maintain thousands of variants of the nodejs binary, but there are still some people and companies that, for whatever legitimate or illegitimate reason still use 32-bit only versions of Windows or other software and it'd be great if those who need it could just build their own binaries.

**Comment by jesec** [comment]
See the CI workflows.
