### ISSUE TITLE
how to build node12.2.0-linux-armv7

### ISSUE THREAD

**Issue by JoahTheron** [vercel/pkg-fetch#111]
`$ pkg . -t node12.2.0-linux-armv7 --output dist/Linux
> pkg@4.4.9
> Fetching base Node.js binaries to PKG_CACHE_PATH

> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.2.0-win-armv7
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-win-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-win-armv7"}
> Building base binary from source:
  built-v12.2.0-win-armv7
> Error! Not able to build for 'armv7' here, only for 'x64'
`

i don't get it why it always tries to fetch win binaries.

**Comment by zaherg** [comment]
To build ARM arch distribution of your application you need to do it on an ARM device like Raspberry PI or something on the cloud.

since you are on `X64` arch device you can only target `x64` arch devices.

hope this help

**Comment by RootWater** [comment]
Did the host solve it?

**Comment by JoahTheron** [comment]
I solved it by building it on the raspberryPI.
