### ISSUE TITLE
Please support latest v12 node version (current is 12.21.0)

### ISSUE THREAD

**Issue by xanonid** [vercel/pkg-fetch#114]
There were several security updates since the last 12.18.1 release (cf. https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#2021-02-23-version-12210-erbium-lts-richardlau ) which seems to be the last v12 version that pkg supports. 
The PR #105 seems to be stale. Beside this, @alexk111 seems to have started a fork to support newer v14 version.

Is there are plan to stay security-wise more up-to-date with at least some node versions or does this depend solely on third-party contributions?

**Comment by leerob** [comment]
Hey! I'm open to reviewing PRs if you'd like to help contribute 👍

**Comment by leerob** [comment]
@hipstersmoothie is also assisting.

**Comment by jgehrcke** [comment]
related for v14: https://github.com/vercel/pkg/issues/986
