### ISSUE TITLE
Please create patch for 14.16.0

### ISSUE THREAD

**Issue by theaquarian007** [vercel/pkg-fetch#117]
I tried using the 14.4.0 file to patch 14.16.0. I got the following error:
patching file src/node_main.cc
Hunk #1 FAILED at 20.
Hunk #2 succeeded at 82 (offset 12 lines).
Hunk #3 succeeded at 136 (offset 12 lines).
1 out of 3 hunks FAILED -- saving rejects to file src/node_main.cc.rej
patching file src/node_options.cc
Hunk #1 succeeded at 230 (offset -3 lines).
> Error! Error: patch failed with code 1
    at ChildProcess.<anonymous> (D:\workdir\aws\pkg-fetch\lib-es5\spawn.js:68:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

Please support 14.16.0.

**Comment by david-mohr** [comment]
I've gotten the patch to apply (see attached), but I get an error during testing of `pkg`:

```
/opt/github/pkg/test/test-50-ast-parsing-2/main.js ok
pkg/prelude/bootstrap.js:1248
      throw error;
      ^

Error: Cannot find module 'escodegen'
Require stack:
- /snapshot/pkg/lib-es5/detector.js
- /snapshot/pkg/test/test-50-ast-parsing/test-x-index.js
```

file:///opt/github/pkg-fetch/patches/node.v14.16.0.cpp.patch

**Comment by david-mohr** [comment]
major thing I noticed was that `internalModuleReadJSON` was missing in `node/lib/internal/modules/cjs/loader.js`

**Comment by david-mohr** [comment]
Ok, I have found the errant function and I think I've fixed it. This patch seems to work well.

[node.v14.16.0.cpp.patch.txt](https://github.com/vercel/pkg-fetch/files/6161886/node.v14.16.0.cpp.patch.txt)

**Comment by robertsLando** [comment]
@david-mohr PR?
