### ISSUE TITLE
NPM release planned?

### ISSUE THREAD

**Issue by pablitovicente** [vercel/pkg-fetch#125]
Is there an NPM release planned in the near future? 

For node 14 the published version uses 14.4.0 that includes some vulnerabilities and this PR https://github.com/vercel/pkg-fetch/pull/118 just added support for 14.16.0 which fixes them.

**Comment by leerob** [comment]
Yes, there is.

**Comment by robertsLando** [comment]
@leerob I would have released a patch instead of a minor, the minor/major causes a new folder in cache..

**Comment by leerob** [comment]
We're not patching though, we're adding new things. There's a bunch of new versions to choose from.

**Comment by leerob** [comment]
https://github.com/vercel/pkg-fetch/releases/tag/2.7.0

**Comment by robertsLando** [comment]
I think we should think about using major version as folder so, do you agree? I'm speaking about cache folder. ATM if you update pkg cache inside pkg it will have no binary, we should copy binaries from 2.6 assets

**Comment by leerob** [comment]
I don't understand the implementation well enough (I'm just getting started learning about these projects). I will defer to you.

**Comment by robertsLando** [comment]
@leerob ATM when pkg uses pkg fetch to get binaries it looks in releases assets, them are grouped in minor/major releases, this mean that if you update pkg-fetch in pkg now it will look in 2.7 releases assets and will find 0 node binaries causing all process to buiild nodejs from source. 

What you should do now is to copy all releases from 2.6 to 2.7
