### ISSUE TITLE
Failure executing pkg: Error! 404 Not Found

### ISSUE THREAD

**Issue by evalkering-mindesk** [vercel/pkg-fetch#134]
Hi, while trying to build our project, one of the steps is to convert our node-based application into an win32 executable. We use `pkg` for that. However, since yesterday, it seems to be failing with the following error:
```
C:\...\>npx pkg . -t win --out-path dist                      
npx: installed 173 in 12.245s
> pkg@4.5.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.16.0-win-x64     [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v14.16.0-win-x64
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.16.0-win-x64"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.16.0-win-x64"}
> Building base binary from source:
  built-v14.16.0-win-x64
> Cloning Node.js repository from GitHub...
  git                          [                    ] 0%^CTerminate batch job (Y/N)? 
```

I'm aware of the recent faulty release of 2.7.0 that caused this, and the subsequent 2.6.10 release that was supposed to fix this issue. However, it still seems to be failing.

As we are about to release a new version of our product, is there any work around available such that we can move on, like specifying specific versions of pkg and/or pkg-fetch in our package.json?

**Comment by ipapast** [comment]
Hey, I hope this helps.
https://github.com/vercel/pkg/issues/1098#issuecomment-807377644

You could also try to target a [specific version of win](https://github.com/vercel/pkg-fetch/releases/tag/v2.6) you see in the assets like the example above

**Comment by robertsLando** [comment]
I'm working to fix this, for now pick the suggestion by @ipapast

**Comment by alexpavlovich** [comment]
@robertsLando it would be more convenient if you would close the issue after the fix was committed, so the participants could be notified about the fix

**Comment by evalkering-mindesk** [comment]
@ipapast , you suggestion https://github.com/vercel/pkg-fetch/issues/134#issuecomment-808113169 seems to be working. If I change the command to:
```npx pkg . -t node14.4.0-win --out-path dist```
it works.

Thanks!

**Comment by robertsLando** [comment]
@alexpavlovich sorry If I didn't explained well but there are already multiple issue regarding this, I close this as a duplicate.

**Comment by alexpavlovich** [comment]
@robertsLando okay, can you give a link for the main issue, bc I'm waiting for this issue to be solved and want to be notified)

**Comment by robertsLando** [comment]
https://github.com/vercel/pkg-fetch/issues/137
