### ISSUE TITLE
Add self-hosted GitHub Action runner for arm64 support

### ISSUE THREAD

**Issue by leerob** [vercel/pkg-fetch#148]
https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

**Comment by robertsLando** [comment]
Did you ask to vercel for them?

**Comment by nwtgck** [comment]
Hi, I'm a pkg user.

For arm64 support without self-hosted runner, you may use the code below to get ARM environement in GitHub Actions.

https://github.com/nwtgck/github-actions-arm-with-docker-prac/blob/d49fb87ff12589e49e5f7b0e6eb2550139561138/.github/workflows/ci.yml#L7-L18

I automated to build arm executable using pkg, pkg-fetch.
https://github.com/nwtgck/piping-server-pkg/blob/0598de51bd01ca301eee3d38b4d2c6029831c847/.github/workflows/ci.yml#L24-L45

**Comment by nwtgck** [comment]
Thanks. Now I understand why self-hosted runner is necessary.

**Comment by jesec** [comment]
Plus, your repo does not compile Node.js binaries. You fetch the binaries from this repo. 

This repo has to compile the Node.js from source.

**Comment by jesec** [comment]
Travis has credit limit, which we are almost certainly going to exceed.

**Comment by baparham** [comment]
I'm going to close this for now. It's still probably going to be a issue just under the surface and maybe someday if we keep seeing arm timeouts cross compiling (or the binaries start breaking for whatever reason) we can look at doing a similar approach to what Jesse did with the runners in his fork.
