### ISSUE TITLE
Releasing 3.0.0

### ISSUE THREAD

**Issue by leerob** [vercel/pkg-fetch#155]
Let's all be on the same page for what we want to include in 3.0, how we'll release it, and what changes we need to communicate/instructions in the changelog.

https://github.com/vercel/pkg-fetch/pull/153#issue-608073780

**Comment by jesec** [comment]
Let me fire workflows and see how things go. 

BTW:
```
to nodejs-sec

# Summary                                                                       
                                                                                
The Node.js project will release new versions of all supported release lines on or shortly after Tuesday, April 6th, 2021.
                                                                                
* Three High severity issues                                                    
                                                                                
## Impact                                                                       
                                                                                
The 15.x release line of Node.js is vulnerable to two high severity issues.     
                                                                                
The 14.x release line of Node.js is vulnerable to three high severity issues.   
                                                                                
The 12.x release line of Node.js is vulnerable to three high severity issues.   
                                                                                
The 10.x release line of Node.js is vulnerable to three high severity issues.   
                                                                                
## Release timing                                                               
                                                                                
Releases will be available at, or shortly after, Tuesday, April 6th, 2021. 
```

We might want to wait a while, so we don't have to do it again later. I also plan to improve the workflows a bit, so you don't have to manually do `built-* -> node-*`.

**Comment by jesec** [comment]
@leerob We need those tokens in repository secrets instead of env secrets.

**Comment by leerob** [comment]
@jesec done 👍

**Comment by leerob** [comment]
And agree on waiting so we can include that!

**Comment by jesec** [comment]
Time to do the bins. 

https://github.com/vercel/pkg-fetch/actions/runs/726264982

https://github.com/vercel/pkg-fetch/actions/runs/726265318

https://github.com/vercel/pkg-fetch/actions/runs/726265537



If things go well, @leerob please proceed to release.

**Comment by jesec** [comment]
`unexpected status: 503 Service Unavailable`

:( not our fault. The container registry is under load. I will run the workflows again.

**Comment by jesec** [comment]
@leerob Binaries are ready.

**Comment by robertsLando** [comment]
@leerob IMO we should completely remove from npm and here relese 2.6.10 to prevent many breaking changes with older pkg versions. When we will be ready we will directly release 3.0.0 version and a 5.0.0 version of pkg

**Comment by jesec** [comment]
FYI: It is impossible to pull a version. We can only re-release an old revision as the new one. 

I agree that we should do that, and mark the breaking versions as deprecated.

**Comment by leerob** [comment]
Created the release: https://github.com/vercel/pkg-fetch/releases/tag/3.0.0

Am I supposed to upload the contents of the .zip files from the GH Actions runs or the contents inside?

**Comment by jesec** [comment]
> Created the release: https://github.com/vercel/pkg-fetch/releases/tag/3.0.0
> 
> Am I supposed to upload the contents of the .zip files from the GH Actions runs or the contents inside?
> 
> Let me know if anything needs to be added to the release changelog that's missing.

We need contents of `.zip` instead of `.zip`. Each `.zip` should contain an executable and a `.sha256sum` hash file. @leerob Please upload both of them, and remove `.zip` files from Release pages.

**Comment by leerob** [comment]
Can do. Also published to NPM and deprecated 2.6.10.

**Comment by jesec** [comment]
Cool. Thanks.

With #160 merged, we may need to release a new version, though. 

https://github.com/vercel/pkg-fetch/actions/runs/729906687

https://github.com/vercel/pkg-fetch/actions/runs/729906991

https://github.com/vercel/pkg-fetch/actions/runs/729907251

Or we can do that later along with other changes.

**Comment by jesec** [comment]
I agree.

**Comment by jesec** [comment]
The tag does not conform to what was defined in `places.ts`, unfortunately. :(

**Comment by jesec** [comment]
It has to be exactly `vMAJOR.MINOR`. So `v3.0` is the correct one here. This only applies to Github Releases.

**Comment by jesec** [comment]
I retagged it to `v3.0` and `v3.0.0`.

**Comment by leerob** [comment]
To confirm, I should cut 3.0.1 now?

**Comment by jesec** [comment]
Go ahead. I will remove the binaries from the Releases, so we can rerun the workflows to build new binaries.

**Comment by jesec** [comment]
New binaries will be available at:

https://github.com/vercel/pkg-fetch/actions/runs/730223721

https://github.com/vercel/pkg-fetch/actions/runs/730226753

https://github.com/vercel/pkg-fetch/actions/runs/730226849

**Comment by robertsLando** [comment]
@leerob

**Comment by leerob** [comment]
Tagged 3.0.1, added binaries, and pushed to NPM 👍

**Comment by jesec** [comment]
umm...

https://github.com/vercel/pkg-fetch/issues/155#issuecomment-815905331 .

**Comment by jesec** [comment]
ping @leerob .

**Comment by leerob** [comment]
I'm not following - why don't we just change pkg to accept `3.0.1` as the version?

**Comment by jesec** [comment]
I believe the reason is that typically only major or minor versions are supposed to change the binaries. Plus, it is a time-consuming process to build and upload binaries. You would not want to do that every time with patch releases that don't change binaries.

All previous tags follow the convention: https://github.com/vercel/pkg-fetch/tags . Of course we can change that, but that requires another version.

**Comment by leerob** [comment]
Sounds good. I'm fine with your proposal for keeping it as 3.0. I will make sure to tag as minor versions going forward.

**Comment by jesec** [comment]
OK. Retagged to `v3.0.1`, uploaded binaries to `v3.0` release and appended changelogs of `v3.0.1`. 

We can still tag patch releases in Git and release patch releases to npm. We just can't not make the tag a Github Release. All Github Releases have to be exactly `vMAJOR.MINOR`.
