### ISSUE TITLE
Automatic patch bumps

### ISSUE THREAD

**Issue by robertsLando** [vercel/pkg-fetch#159]
What are your toughts about creating a workflow that checkes latest available nodejs versions and based on them creates a PR with the updated patches? By default it will just bump patches versions but then we could also create a workflow that tests the patches to make them valid

**Comment by robertsLando** [comment]
cc @jesec @leerob

**Comment by jesec** [comment]
That does need a human.

**Comment by pablitovicente** [comment]
Is there a guide somewhere on how to create this patches, or at least the ones that involve JS, so people can start collaborating with those in case new ones are needed?

**Comment by robertsLando** [comment]
> Is there a guide somewhere on how to create this patches, or at least the ones that involve JS, so people can start collaborating with those in case new ones are needed?

I think the best guide is to see the changes applied, essentially it allows to start nodejs sourceless but as we dunno how nodejs will edit those lines in future is hard to write a guide on that

**Comment by robertsLando** [comment]
> That does need a human.

the idea behind this was just to try to apply patches as them are with the next nodejs versions, if the patch works itr means that it is still valid for that version and doesn't require an edit. This is the idea behind this

**Comment by jesec** [comment]
Based on my experience so far, I don't believe this can be automated. 

To further reduce the maintenance burden, we would have to collaborate with upstream. See https://github.com/nodejs/next-10/issues/99.
