### ISSUE TITLE
Alpine binaries not available on 3.x 

### ISSUE THREAD

**Issue by Mogztter** [vercel/pkg-fetch#165]
Hello,

I noticed that Alpine binaries are not available when using `pkg-fetch` 3.0.1:

```
$ npx pkg-fetch@3.0.1 -n node10 -p alpine -a x64
npx : 31 installé(s) en 3.363s
  fetched-v10.24.1-alpine-x64  [                    ] 0%
> Error! 404
> Not found in remote cache:
  {"tag":"v3.0","name":"node-v10.24.1-alpine-x64"}
> Building base binary from source:
  built-v10.24.1-alpine-x64
> Error! Not able to build for 'alpine' here, only for 'linux'
```

Here's the same command with `pkg-fetch` 2.6.0:

```
$ npx pkg-fetch@2.6.0 -n node10 -p alpine -a x64
  fetched-v10.15.3-alpine-x64  [====================] 100%
> /home/guillaume/.pkg-cache/v2.6/fetched-v10.15.3-alpine-x64
```

Is it intended? is there a workaround?

Thanks!

**Comment by jesec** [comment]
This is expected.

Currently there is no workflow that builds alpine binaries.

**Comment by Mogztter** [comment]
Thanks for your answer.

Would you be open to add a workflow to build alpine binaries? I guess we could create a `Dockerfile.alpine` to build binaries? (similar to https://github.com/vercel/pkg-fetch/blob/master/Dockerfile.linux).

**Comment by jesec** [comment]
Go ahead. Though, we need binaries for multiple architectures.
