### ISSUE TITLE
Is the publish workflow shareable?

### ISSUE THREAD

**Issue by sramam** [vercel/pkg-fetch#176]
I wanted to enable the inspector in the binaries and need to publish the generated binaries to my fork. 
A meta goal is to keep the modifications to a minimum. 

It would help to study the publish workflow used in the upstream package.

**Comment by robertsLando** [comment]
check .github/workflows

**Comment by sramam** [comment]
Thanks for the quick response.

I understand how the binaries are built.

It's that I don't see the binaries being uploaded to the release directory, just as build artifacts. 
Doesn't some pre-publish script have to collate all the (new) builds and upload the files to the release directory?
Presumably, the same script updates the expected checksums?

**Comment by robertsLando** [comment]
Binaires are manually uploaded along with hash files
