### ISSUE TITLE
Option to skip hash check

### ISSUE THREAD

**Issue by klugerama** [vercel/pkg-fetch#188]
We are using ResourceHacker to modify the node binary after download, to change the icon and metadata. Running it after pkg builds doesn't work - it results in a broken binary. However, we've been running it on the downloaded node binary and it works.

Would there be a way to skip the hash check, so that pkg-fetch doesn't automatically clobber the binary that we just modified?

**Comment by jesec** [comment]
Rename from `fetched-*` to `built-*`.

**Comment by Hypfer** [comment]
@klugerama See https://github.com/vercel/pkg-fetch/pull/169 for an explaination why pkg-fetch behaves like it behaves

**Comment by baparham** [comment]
> Rename from `fetched-*` to `built-*`.

To have a bit more explanation on this, does this mean that `pkg` then assumes you've built the binary locally from source, so it then prioritizes using the `build-*` version over the `fetched-*` version?

**Comment by SBeyeMHP** [comment]
Yes

**Comment by Hypfer** [comment]
Yes

**Comment by evanmosby** [comment]
Confirming the rename works like a champ! Thank you very much!

**Comment by baparham** [comment]
It's worth noting that if both the fetched version and the built version
exist in the cache, you have to add `--build` to the call to pkg to tell it
not to use the the fetched binary.

Thanks for the workaround, it works for my workflow as well.

**Comment by klugerama** [comment]
@Hypfer I understand why this is done - it's a valuable addition. However, once the binary is downloaded using `.need()` I would like the ability to skip the hash check (as an option only) during `pkg.exec()`, since the originally downloaded binary has already been checked.

@jesec This is a good workaround for now, thank you!

**Comment by jesec** [comment]
> > Rename from `fetched-*` to `built-*`.
> 
> To have a bit more explanation on this, does this mean that `pkg` then assumes you've built the binary locally from source, so it then prioritizes using the `built-*` version over the `fetched-*` version? [edit: fixed typo]

No. `fetched-*` binaries have higher priority if they are present. It is just `pkg-fetch` won't check hashes of locally `built-*` binaries. 

We are not going to remove the hardcoded hash check for `fetched-*` binaries.
