### ISSUE TITLE
Single-Branch is unavailable with very legacy git version

### ISSUE THREAD

**Issue by imyelo** [vercel/pkg-fetch#204]
`git clone --single-branch` is unavailable in git with version < 1.7.10, which will crash like:

![image](https://user-images.githubusercontent.com/2399123/123375541-7dbbea80-d5bb-11eb-97a6-0c0024faf23e.png)

- https://github.com/vercel/pkg-fetch/blob/27e00d1/lib/build.ts#L72
- https://stackoverflow.com/a/9920956
- https://lkml.org/lkml/2012/3/28/418

**Comment by jesec** [comment]
Git 1.7.10 was released in 2012. It is a bit surprising to me that there are users who are on such old platform. 

Nonetheless, I think the dependency on Git is probably not really necessary when we can simply fetch the Node.js source archive. 

I will take a look.
