### ISSUE TITLE
Dynamic loading not supported

### ISSUE THREAD

**Issue by sgoll** [vercel/pkg-fetch#205]
Builds for target platform `linuxstatic` (e.g. `node14.17.0-linuxstatic-armv7`) complete without error but fail to run. I guess this happens when native packages are involved (`better-sqlite3` in the example):

```
$ ./pkg-linuxstatic
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: Dynamic loading not supported
    at tryImporting (pkg/prelude/bootstrap.js:2028:37)
    at tryImporting (pkg/prelude/bootstrap.js:2080:16)
    at process.dlopen (pkg/prelude/bootstrap.js:2103:7)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at bindings (/snapshot/pkg-linuxstatic/node_modules/bindings/bindings.js:112:48)
```

I created a minimal reproduction at [sgoll/pkg-linuxstatic](https://github.com/sgoll/pkg-linuxstatic) with GitHub Actions that produce the failing artifact.

See jesec/pkg-fetch#1

**Comment by jesec** [comment]
The error message is crystal clear: `Dynamic loading not supported`.

and, README of pkg (https://github.com/vercel/pkg#native-addons):

> Note that fully static Node binaries are not capable of loading native bindings, so you may not use Node bindings with `linuxstatic`.

Be aware that armv7 platform is supported on the best effort basis. There is only linuxstatic executable, and no further action would be taken.

**Comment by sgoll** [comment]
@jesec Thank you for your kind response.

It is sometimes not entirely clear when a larger project ends up with native bindings among its (indirect) dependencies. Is there a way to have `pkg` check those dependencies upfront when it walks the dependency tree and abort compilation in that case?

To me it was rather surprising to have the build succeed but then fail at runtime.

**Comment by jesec** [comment]
It is rather complicated to implement a function to detect native bindings in dependencies. Support for native bindings is fairly recent and comes with caveats, and we expect users to read README.

JavaScript is a dynamically typed language, and pkg does not change that. You should be aware that the "compile" will not point out all sorts of errors you may have in the runtime.
