### ISSUE TITLE
Support win x86

### ISSUE THREAD

**Issue by bnobre** [vercel/pkg-fetch#206]
I noticed that there is no support for Node win x86, only x64. That's right?

**Comment by jesec** [comment]
We will not support x86.

**Comment by bnobre** [comment]
> We will not support x86 (32-bit).

Hi jesec. Why?

**Comment by jesec** [comment]
Because it is dead. There is no legitimate use case, and we would like to save our energy for more common cases. 

Please upgrade your platform.

**Comment by bnobre** [comment]
> Because it is dead. There is no legitimate use case, and we would like to save our energy for more common cases.
> 
> Please upgrade your platform.

Thx jesec, i will.

I have read that this technique of packaging nodejs and our app does not guarantee the protection of the source code... is it true?

**Comment by jesec** [comment]
> > Because it is dead. There is no legitimate use case, and we would like to save our energy for more common cases.
> > Please upgrade your platform.
> 
> Thx jesec, i will.
> 
> I have read that this technique of packaging nodejs and our app does not guarantee the protection of the source code... is it true?

No technique can "guarantee" protection of your source code.

With enough time, efforts, skills and motivation, competent engineers can always derive the necessary information from the machine code. Just take a look at the video game industry: even with hundreds of millions at stake, and the best encryption/obfuscation techniques (i.e. Denuvo) that apply to compiled/native languages (e.g. C++, which is arguably much difficult to reverse engineer than JavaScript), the software gets reverse engineered. 

However, one could say that `pkg` is much better than common obfuscations/minimization, as `pkg` pre-compiles the source code to byte/machine code. That would protect your source code, to some extent.

**Comment by bnobre** [comment]
> > > Because it is dead. There is no legitimate use case, and we would like to save our energy for more common cases.
> > > Please upgrade your platform.
> > 
> > 
> > Thx jesec, i will.
> > I have read that this technique of packaging nodejs and our app does not guarantee the protection of the source code... is it true?
> 
> No technique can "guarantee" protection of your source code.
> 
> With enough time, efforts, skills and motivation, competent engineers can always derive the necessary information from the machine code. Just take a look at the video game industry: even with hundreds of millions at stake, and the best encryption/obfuscation techniques (i.e. Denuvo) that apply to compiled/native languages (e.g. C++, which is arguably much difficult to reverse engineer than JavaScript), the software gets reverse engineered.
> 
> However, one could say that `pkg` is much better than common obfuscations/minimization, as `pkg` pre-compiles the source code to byte/machine code. That would protect your source code, to some extent.

It's true.

The pkg pre-compiles the source code to byte/machine code equal https://github.com/bytenode/bytenode?

**Comment by jesec** [comment]
pkg does not depend on `bytenode`. but, the philosophy looks similar. 

I am not able to give you a definitive answer. As I said, there is no way to guarantee protection of your source code.

**Comment by U-siro** [comment]
@jesec Pleaase reconsider it. our external dll are 32 bit only.
