### ISSUE TITLE
Windows x86 prebuilt node binaries

### ISSUE THREAD

**Issue by lucavictor220** [vercel/pkg-fetch#207]
Is there a plan to support x86 architecture for the pre-built node binaries? After a major update of pkg-fetch you added expected.ts file that doesn't list any x86 node binaries. We would like to update to v14.17.2 of node, but at the moment it's impossible, because you don't provide this binary for windows x86 .

May I kindly ask you to resume support for x86 architecture or provide a comprehensive documentation how to build them on our own?

**Comment by jesec** [comment]
No. There is no plan to support x86 (32-bit). You are on your own. 

and, please use the search function. there is a lot of duplicate issues.

**Comment by brandonros** [comment]
https://github.com/brandonros/pkg-fetch/tree/v3.2-x86
