### ISSUE TITLE
Github Workflow end of support for windows-2016

### ISSUE THREAD

**Issue by axi92** [vercel/pkg-fetch#221]
Github will remove according to this blog post the windows-2016 support next year.
https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/

I just want to raise awareness for that if it is not already on the road-map.

https://github.com/vercel/pkg-fetch/blob/ef24fc5cd847c3ffb5a1df801f4b442a2ea210f1/.github/workflows/build-windows.yml#L8

**Comment by jesec** [comment]
We are planning to drop EOL-ed Node 10 and 12, and the `windows-2016` would not be used after that. 

https://github.com/vercel/pkg-fetch/blob/ef24fc5cd847c3ffb5a1df801f4b442a2ea210f1/.github/workflows/build-windows.yml#L48

**Comment by axi92** [comment]
OK nice, you may close this issue then =)
