### ISSUE TITLE
`linuxstatic` binaries of v3.2.4 are defective

### ISSUE THREAD

**Issue by jesec** [vercel/pkg-fetch#223]
`linuxstatic` binaries of v3.2.4 are defective. 

The newer GCC compiler is smarter. It figures out that `BAKERY` placeholder is not actually used and omit it. However, `pkg` does need the placeholder to override the launch arguments of Node.js.

```
volatile char* BAKERY = (volatile char*) "\0// BAKERY // BAKERY " \
  "// BAKERY // BAKERY // BAKERY // BAKERY // BAKERY // BAKERY " \
  "// BAKERY // BAKERY // BAKERY // BAKERY // BAKERY // BAKERY " \
  "// BAKERY // BAKERY // BAKERY // BAKERY // BAKERY // BAKERY ";
...
  char* bakery = (char*) BAKERY;
  while (true) {
    size_t width = strlen2(bakery);
    if (width == 0) break;
    nargv[c++] = bakery;
    bakery += width + 1;
  }
...
```

I am honestly surprised by the fact that the compiler can figure that out at compile-time.

This is a repeat of the earlier issue with Clang (#199). For GCC, only static binaries are affected by this issue.

**Comment by jesec** [comment]
In preparation for a new patch release, I removed the defective binaries.

**Comment by schlomo** [comment]
Is that the reason why
```
e26b713c159d38b09ba8db95e4c8220653386aad7bc6ec0921f6b6b20f4710c5  node-v16.12.0-linuxstatic-armv7
```
(and potentially others) are missing from the files but still present in the signed list?

**Comment by jesec** [comment]
> In preparation for a new patch release, I removed the defective binaries.

Yes.

**Comment by jesec** [comment]
@leerob When you have time, please publish 3.2.5 to npm. Thanks!

**Comment by jesec** [comment]
ping @leerob .

**Comment by si458** [comment]
@leerob ping
pkg keeps downloading node v16.12.0 because of v3.2.4,
please release v3.2.5!

**Comment by si458** [comment]
@jesec im assuming this is why i cant bundle v16.13.0 from prebuilts yet?
i download `node-v16.13.0-win-x64` as `built-v16.13.0-win-x64` but then running exec,
it keeps trying to build from scratch of v16.12.0
```
> pkg@5.4.1
> Building base binary from source:
  built-v16.12.0-win-x64
> Cloning Node.js repository from GitHub...
```

**Comment by robertsLando** [comment]
@leerob even If I appreciate your work here and I understand that you are so busy this lack of response/support is kind of demotivating users to contribute to `pkg` and it's slowing down updates.

@jesec Giving that we are the most active here, what about create a fork of pkg-fetch and pkg and keep them maintained by our own? I know you already had forked those project so you could keep them as your repos, it doesn't make any difference to me I just want to don't see this project die.

**Comment by Niek** [comment]
I have to agree with @robertsLando - if this was about some feature request I would understand. But this issue is about broken packages that are unfixed for 3 weeks even though the fix is available.

**Comment by leerob** [comment]
Sorry about the slow response - will cut a new release when I’m home from vacation (there’s a holiday in the United States).

**Comment by leerob** [comment]
In the future, emailing me directly would be a better option. I’m overwhelmed with GitHub notifications most days so things slip by.

**Comment by leerob** [comment]
Published -> https://www.npmjs.com/package/pkg-fetch/v/3.2.5

**Comment by jesec** [comment]
👍 I can totally understand. It is difficult to be productive during holiday, especially after a busy pre-holiday wrapping up. 

(i didn't turn on GitHub notifications either. it is too noisy when you are involved in too many projects.)

Got it. Next time, I will send an email to you when a new release is ready.

**Comment by leerob** [comment]
Thank for you understanding @jesec ❤️
