### ISSUE TITLE
openssl fail the build

### ISSUE THREAD

**Issue by ramymabrouk** [vercel/pkg-fetch#228]
i have tried multiple node versions on armv7 but i always get this error when makeing openssl

`/usr/bin/ld: internal error ../../ld/ldlang.c 6409
collect2: error: ld returned 1 exit status
deps/openssl/openssl-cli.target.mk:230: recipe for target '/mnt/ext1/pkgtmp/pkg.7067651a3602a6fe2644395f/node/out/Release/openssl-cli' failed
make[1]: *** [/mnt/ext1/pkgtmp/pkg.7067651a3602a6fe2644395f/node/out/Release/openssl-cli] Error 1
Makefile:109: recipe for target 'node' failed
make: *** [node] Error 2
strip: '/mnt/ext1/pkgtmp/pkg.7067651a3602a6fe2644395f/node/out/Release/node': No such file
> Error! Error: ENOENT: no such file or directory, open '/mnt/ext1/pkgtmp/pkg.7067651a3602a6fe2644395f/node/out/Release/node'
`
any help?

**Comment by jesec** [comment]
armv7 is not a supported architecture.
