### ISSUE TITLE
Can some one update me before i start something need less

### ISSUE THREAD

**Issue by frank-dspeed** [vercel/pkg-fetch#235]
i find here no x32 binarys but i need them to execute pkg and build for x32 i do not plan to build that in my own ci always 

why does this not use nodejs x32 windows builds when i run pkg win-x86 ? is there something blocking i do not fully get it 

#172 

the nodejs website offers the builds can we use that ? is there something else that i need to know?

**Comment by jesec** [comment]
Please use the search function.

#206
