### ISSUE TITLE
Re-enable cross compiling for ARM

### ISSUE THREAD

**Issue by baparham** [vercel/pkg-fetch#276]
Right now we have no runners for arm builds, and the cross compiling stopped working a year or two ago (hence the introduction of @jesec fork's self-hosted arm runners), so maybe if somebody needs that they could work up a PR helping re-enable cross compiling from the steps outlined at [Node.js's BUILDING.md file](https://github.com/nodejs/node/blob/main/BUILDING.md)

_Originally posted by @baparham in https://github.com/vercel/pkg-fetch/issues/257#issuecomment-1433740037_

Any help anyone can provide to work up a PR re-enabling cross compiling following the directions at the Node.js building.md file would be greatly appreciated.

Presumably you can just fork the repo, enable actions in your repo, and run the builds yourself on GitHub's hosted runners to verify things work as expected as you develop your PR.

**Comment by robertsLando** [comment]
An option could be using buildjet: https://buildjet.com/for-github-actions/docs/runners#arm

**Comment by baparham** [comment]
Yeah, I'm also just noticing that the support only calls out cross compiling for arml7, not arm64. doesn't mean it's not possible, but not already being done.

**Comment by baparham** [comment]
I mean, they have lots of nice words on https://buildjet.com/for-github-actions/security but _how can we be sure?_

Seems tough to commit to a third party runner provider if it's not one of the big players like aws, azure or google cloud (outside of github of course, but that's just azure). The risk is not so much exposure of private IP, but of the integrity of binaries produced on said servers.

**Comment by robertsLando** [comment]
I'm not a security expert so I cannot say so much about that, BTW in the meanwhile we could setup a workflow using https://github.com/uraimo/run-on-arch-action ? 

I already used it and works great

**Comment by robertsLando** [comment]
I'm actually using it on my repo to create a package of my app: https://github.com/zwave-js/zwave-js-ui/blob/master/.github/workflows/package_armv7.yml#L37

Specifically I'm using it to build node native addons and then I download the `armv7` nodejs patch directly from my other repo I use to create the nodejs patches (and host them) about armv7 archs: https://github.com/yao-pkg/pkg-binaries

ATM that uses buildx but I'm planning to switch to use runs on arch soon

**Comment by robertsLando** [comment]
@baparham Check it out: https://github.com/yao-pkg/pkg-binaries/actions/runs/4204469254/jobs/7295186181

**Comment by baparham** [comment]
could look at circle ci, they say "Open source projects can access up to 400,000 credits per month (equivalent to 80,000 build minutes) to use on Linux, Arm, and Docker."

**Comment by baparham** [comment]
at least for arm

**Comment by robertsLando** [comment]
Could be an option yeah!

**Comment by baparham** [comment]
trying something here: https://github.com/baparham/pkg-fetch/actions/runs/4210853275/jobs/7308803866

**Comment by baparham** [comment]
I'm trying out a circle ci build in my fork here: https://app.circleci.com/pipelines/github/baparham/pkg-fetch/9/workflows/635fd9fb-6b5d-404d-bd63-fc2868f778ff/jobs/2

If that works and is a way forward, we'll need @leerob to step in and figure out how we can authorize the CircleCI github app in this repo and/or the Vercel org. I don't have the permissions to add this repo to a CircleCI project.

**Comment by baparham** [comment]
Hm, ok, CircleCI has a 1 hour limit for the free tier, even for open source projects, so that may be a non-starter. the ninja builds in #278 aren't dropping those times to less than an hour either.

**Comment by robertsLando** [comment]
Ok circle CI is not an option as 1h is too less.

I don't understand BTW what this error means: https://github.com/baparham/pkg-fetch/actions/runs/4210853275/jobs/7308803866#step:3:27836

It's strange it doens't work, any clue?

**Comment by baparham** [comment]
successfully cross compiled for linux arm over in https://github.com/baparham/pkg-fetch/actions/runs/4263530646/jobs/7420388746 so now I'll renable linuxstatic and alpine to see how it goes 🤞

**Comment by baparham** [comment]
...for node 19 only so far... not sure how the other version ranges will do

**Comment by robertsLando** [comment]
Well done @baparham 💪🏼

**Comment by baparham** [comment]
so far linux, linuxstatic, and macos look good, still waiting on alpine and windows, which also look OK. see the top few workflows running over in https://github.com/baparham/pkg-fetch/actions

**Comment by baparham** [comment]
I can put together a PR for this repo in the next day or two, which I think may unblock a release

@leerob FYI, this is what we are thinking may work for our ARM builds.

**Comment by baparham** [comment]
Anybody have local ARM machines they want to test this out on? Once the builds in https://github.com/baparham/pkg-fetch/actions/runs/4368413726 finish, it would be great if we could get some sort of confirmation that my blind fix actually produces viable binaries! They build, but that's only half the battle...Hopefully the cross compiling still produces binaries that can actually run on arm machines.

**Comment by robertsLando** [comment]
I can
