### ISSUE TITLE
Android Binaries

### ISSUE THREAD

**Issue by ghost** [vercel/pkg-fetch#29]
Do you plan to add binaries for Android Arm? Such as ones that can be run with [Termux](https://termux.com)?

**Comment by shivindera** [comment]
+1

**Comment by robertsLando** [comment]
Here you can find a useful guild and some prebuild binaries: https://github.com/robertsLando/pkg-binaries

**Comment by leerob** [comment]
Hello! Sorry for the extremely late reply here, but we do not plan to add support for Android currently 🙏
