### ISSUE TITLE
Version not updated for pkg-fetch 3.5.1

### ISSUE THREAD

**Issue by rs-siemens** [vercel/pkg-fetch#293]
The version attribute still shows 3.4.2 for the 3.5.1 tag. Please update it.

**Comment by baparham** [comment]
have you tried using 3.5.2? this should be fixed.

**Comment by baparham** [comment]
it seems the tag has not been pushed. I'll figure that out.

**Comment by baparham** [comment]
My mistake, this is now fixed. Thanks for flagging this 🙏
