### ISSUE TITLE
armv6 binaries

### ISSUE THREAD

**Issue by IannothSlurgh** [vercel/pkg-fetch#31]
Hello,

I discovered that the latest release of pkg-fetch (2.5) does not have any armv6 binaries in the downloads section.

The previous release (2.3) did have armv6 binaries.

This causes 404 when you try and compile for armv6. For instance,

`sudo pkg . -t node6-armv6`

causes

```
> pkg@4.3.0-beta.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v6.11.5-linux-armv6  [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.5/uploaded-v2.5-node-v6.11.5-linux-armv6
> Asset not found by direct link:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v6.11.5-linux-armv6"}
> Not found in GitHub releases:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v6.11.5-linux-armv6"}
> Building base binary from source:
  built-v6.11.5-linux-armv6
> Error! Not able to build for 'armv6' here, only for 'armv7'
```

Operating System: Raspbian
Hardware: Raspberry Pi 3

Thanks,
IannothSlurgh

**Comment by DanielRuf** [comment]
Do the linux x64 builds work? If not this is also a reason why the unit tests of zeit/pkg fail.

**Comment by mini-eggs** [comment]
Seeing the same issue with armv7 as well.

`pkg build/main.js --out-path dist --targets x64,x86,armv6,armv7`

is throwing 404 errors while

`pkg build/main.js --out-path dist --targets x64,x86`

is fine.

Here's a snippet of of the error received.

```bash 
> pkg@4.3.0-beta.5
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v9.2.1-linux-armv6   [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.5/uploaded-v2.5-node-v9.2.1-linux-armv6
> Asset not found by direct link:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v9.2.1-linux-armv6"}
> Not found in GitHub releases:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v9.2.1-linux-armv6"}
> Building base binary from source:
  built-v9.2.1-linux-armv6
> Error! Not able to build for 'armv6' here, only for 'x64'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! nodegitdockerci@1.0.0 build: `backpack build && pkg build/main.js --out-path dist --targets x64,x86,armv6,armv7`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the nodegitdockerci@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/evan/.npm/_logs/2017-12-31T19_12_43_500Z-debug.log
```

**Comment by joehand** [comment]
Also ran into this issue trying to build armx64.

**Comment by kkota1** [comment]
`sudo npm install -g pkg@4.2.3`

This allowed me to fetch this `node8-linux-armv6`

But I get a bunch of this "Failed to make bytecode node8-armv6 for file..."

**Comment by adonespitogo** [comment]
Anyone knows how to manually create binaries?

**Comment by Einstein42** [comment]
I need armv6 8.2+ so I would like to know this as well.

**Comment by adonespitogo** [comment]
@Einstein42 Try this solution https://github.com/zeit/pkg-fetch/issues/33

**Comment by Einstein42** [comment]
Perfect thanks.

**Comment by robertsLando** [comment]
Here you can find a useful guide to build your own binaries and some prebuild nodejs bin: https://github.com/robertsLando/pkg-binaries

**Comment by jesec** [comment]
No. Only arm64 is officially supported. There is no plan to bring back armv6 or armv7.
