### ISSUE TITLE
Prebuilt arm64 distribution

### ISSUE THREAD

**Issue by iiSeymour** [vercel/pkg-fetch#35]
Would it be possible to provide arm64 v8 prebuilt binaries for node8 and node9?

```
$ pkg -t node8-linux-arm64 example.js 
> pkg@4.3.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v8.9.0-linux-arm64   [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.5/uploaded-v2.5-node-v8.9.0-linux-arm64
> Asset not found by direct link:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v8.9.0-linux-arm64"}
> Not found in GitHub releases:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v8.9.0-linux-arm64"}
> Building base binary from source:
  built-v8.9.0-linux-arm64
```

**Comment by rmp** [comment]
happy to contribute somehow, given instructions.

**Comment by cliveve** [comment]
+1
would also like a procedure to create the uploaded file from pkg-fetch source for armv8. already compiled node 8.11.3 for armv8, just need to know how to create the pkg-fetch please.

**Comment by robertsLando** [comment]
Here you can find the binaries: https://github.com/robertsLando/pkg-binaries

**Comment by kerberjg** [comment]
As mentioned in https://github.com/vercel/pkg/issues/361 native support would be much better, especially with Apple M1 making this arch mainstream and arm7-compat being phased out.

Is there any reason why this can't/won't be implemented?

**Comment by jesec** [comment]
arm64 is now supported.
