### ISSUE TITLE
Windows node 10.x prebuilt binaries timeline

### ISSUE THREAD

**Issue by EricMCornelius** [vercel/pkg-fetch#41]
Hi there,

Thanks so much for the project, it is fantastic to be able to get a cross-platform single node binary built with such little effort.

I was wondering when we might see v10.1.0 prebuilt for windows x86/x64 - currently the releases only exist for macos and linux.

Happy to assist if I can - chomping at the bit to migrate to the new pending LTS for performance improvements.

**Comment by ryandelvecchio** [comment]
I would love this as well. I am running into a lot of issues attempting to build it myself.

**Comment by hipstersmoothie** [comment]
@leerob think this one is stale too. window has the same support as mac/linux in current release
