### ISSUE TITLE
Node Alpine only in x64?

### ISSUE THREAD

**Issue by ricardopolo** [vercel/pkg-fetch#44]
Why you dont support Node Alpine x86?

**Comment by RomanDavlyatshin** [comment]
The conversation seems stale.
@igorklopov can you please respond? Either confirm or deny the possibility of adding binaries for alpine x86.
It would allow a user to decide whether to search for another packaging tool or not.

**Comment by jesec** [comment]
x86 32-bit is dead. Switch to 64-bit.
