### ISSUE TITLE
Node v10.5.0+ support?

### ISSUE THREAD

**Issue by bsparacino** [vercel/pkg-fetch#51]
Any timeline on when there will be a windows binary for v10.5.0 or above?
As of writing this the latest node version is v10.12.0

There is a feature in v10.5.0 that I am using and would like to be able to build with.

**Comment by alexgreenland** [comment]
I'm interested in a binary for the latest LTS or latest current.

**Comment by soryy708** [comment]
Related: https://github.com/zeit/pkg-fetch/issues/41

**Comment by hipstersmoothie** [comment]
@leerob Current release support node 10.15.3. this issue can be closed
