### ISSUE TITLE
LTS Support: How to go about creating a new binary and release?

### ISSUE THREAD

**Issue by alexgreenland** [vercel/pkg-fetch#52]
I'd like to use the latest Node LTS (`v10.13.0`) in `pkg`. This hasn't been uploaded as a release but I'm happy to go about creating one. What's involved in building a binary and creating a release?

I see the [patch](https://github.com/zeit/pkg-fetch/blob/master/patches/node.v10.4.1.cpp.patch) for `v10.4.1`. How would I go about creating a patch for another version, or as this has the same ABI would it be compatible? What steps are followed to make it compatible for `pkg`?

**Comment by VasiliyIsaichkin** [comment]
+1 need 10.14.2 LTS support

**Comment by cjk** [comment]
In the meantime, Node 11.10.1 is current.

**Comment by VasiliyIsaichkin** [comment]
> In the meantime, Node 11.10.1 is current.
Now LTS is 10.15.3, 11.11.0 - current/dev :)

**Comment by aral** [comment]
Has anyone got a solution for using pkg with latest LTS Node? I need `crypto.generateKeyPair()` and that requires node >= v10.12.

**Comment by hipstersmoothie** [comment]
@leerob Current release support node 10.15.3. this issue can be closed
