### ISSUE TITLE
Library for arm64 binaries and others not supported platforms

### ISSUE THREAD

**Issue by robertsLando** [vercel/pkg-fetch#53]
I have created a github repo to place resources that are not aviable by default on pkg and that need to be compiled. 

https://github.com/robertsLando/pkg-binaries

**Comment by danawoodman** [comment]
@igorklopov plans to update binaries to support arm64 and later versions of node? Having users build (which seems to take hours) is unfortunate :/

**Comment by hipstersmoothie** [comment]
@leerob this is a dupe of #35 and can be closed
