### ISSUE TITLE
What is the purpose of the patch files?

### ISSUE THREAD

**Issue by pdulapalli** [vercel/pkg-fetch#55]
I was wondering why the patches needed to be made in the first place. Does stock Node.js not supply the features we need?

-Thanks!

**Comment by robertsLando** [comment]
Them are needed to run nodejs apps "sourceless"

**Comment by pdulapalli** [comment]
Ah, that makes sense

With all the releases of Node.js and their updates, isn't it difficult to keep the patch files up to date?

Wonder if there's an easier alternative?

**Comment by gautaz** [comment]
I just stumbled over this issue and I have the same feeling as @pdulapalli, I made a proposal on this matter (#172).

**Comment by jesec** [comment]
Check the patches yourself. Or https://github.com/nodejs/next-10/issues/99#issuecomment-970674910.

**Comment by gautaz** [comment]
Thanks @jesec for the follow up, I have read the [Next-10-Mini-Summit-18-Nov-2021 transcript](https://hackmd.io/mW7rTTYvREOwGRpOYkXc4w#Next-10-Mini-Summit-18-Nov-2021) and I am looking forward for a better integration with NodeJS :+1:.
