### ISSUE TITLE
Allow overriding GitHub API URL via config/env var

### ISSUE THREAD

**Issue by wbagdon** [vercel/pkg-fetch#59]
For building on a CI agent without access to the internet, we have a mirror of Github release repos set up via Artifactory.
It would be great if it were possible to override the GitHub API URL that is currently hardcoded as can be done in node-sass:
https://github.com/sass/node-sass#binary-configuration-parameters

**Comment by jesec** [comment]
You can share the `.pkg-cache` inside your local network.
