### ISSUE TITLE
how to create the  "node.v10.16.0.cpp.patch"  like pkg-fetch/patches/

### ISSUE THREAD

**Issue by pengchangjiang** [vercel/pkg-fetch#69]
I need to package my project with node.v10.16.0，but not found in pkg-fetch realeas。How to create new binary with specified version, such as node.v10.16.0? How would I go about creating a patch for another version,

**Comment by alxproject** [comment]
here can check binary for 10.16.3
https://github.com/zeit/pkg-fetch/pull/70

**Comment by hipstersmoothie** [comment]
@leerob this one can be close, latest release contains 10.17.0
