### ISSUE TITLE
Build failed due to trying to fetch incorrect node binary

### ISSUE THREAD

**Issue by alextran1502** [vercel/pkg-fetch#71]
I am trying to build for Linux ARMv7 on Window 10 by using this command

`pkg . --output bin/mbta_armv7_$(BUILD_DATE) -t node10-linux-armv7`

It was successfully fetched v10 node for linux armv7 but then it is trying to fetch nodev10-win-armv7 which doesn't exist. 

![image](https://user-images.githubusercontent.com/27055614/65168655-9b354b00-da0a-11e9-8ae5-a507f549db44.png)

Have you guys come across this issue and how to fix it? 

Thanks

**Comment by geomad** [comment]
@alextran1502 you can build cross-platform but not for a different arch

**Comment by jesec** [comment]
There is no way to run the armv7 binary on Windows x86.
