### ISSUE TITLE
Instructions on Readme to allow the community to help

### ISSUE THREAD

**Issue by paulocoghi** [vercel/pkg-fetch#78]
We would like to help maintain `pkg` and `pkg-fetch`, mainly to bring new NodeJS versions, but there aren't instructions on readme on how we can do this.

**Comment by robertsLando** [comment]
@paulocoghi I'm trying to do this with: https://github.com/robertsLando/pkg-binaries

**Comment by paulocoghi** [comment]
Thanks, @robertsLando !

If possible, please mention your project on the two issues referenced above!

**Comment by robertsLando** [comment]
@paulocoghi Done!

**Comment by bfivelson** [comment]
We would also like to help maintain

Is there any documentation on how we can help build patches?

**Comment by robertsLando** [comment]
@bfivelson I have created a new org with @n1ru4l: https://github.com/yao-pkg.

Check open pr/issues

**Comment by leerob** [comment]
Hello! I'm now helping maintain this to merge and resolve issues. I would love any support, especially @robertsLando if you'd like to contribute back 🙏

**Comment by robertsLando** [comment]
Ok no problem
