### ISSUE TITLE
NodeJS 12.16.1 LTS

### ISSUE THREAD

**Issue by awjreynolds** [vercel/pkg-fetch#79]
A number of vulnerabilities were discovered with 12.13.1 that have now been patched in 12.16.1.

Could pkg-fetch be updated with the latest LTS?

**Comment by terryvdgriend** [comment]
I have created a PR with a patched version of Node 12.16.1, which we use currently using https://github.com/zeit/pkg-fetch/pull/80

**Comment by vladiks** [comment]
Would be great to have this merged

**Comment by rauchg** [comment]
@terryvdgriend would you be up for being added as a maintainer of the project?

**Comment by erossignon** [comment]
Apparently, uploaded-v2.6-node-v12.16.1-linux-x64 is missing 

 Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.16.1-win-x64     [====================] 100%
  fetched-v12.16.1-linux-x64   [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.16.1-linux-x64

How can we resolve this ?

**Comment by terryvdgriend** [comment]
@rauchg Sure, we are currently using it in our own products and when a new LTS of Node arrives, we would like to upgrade when we get the chance.

**Comment by rauchg** [comment]
@terryvdgriend Great. We will keep you posted! @igorklopov will be doing some maintenance periodically to keep Node.js versions up to date in `pkg`. Sorry for the delay to everyone in the thread!

**Comment by mkhurramali** [comment]
I have started getting these errors when I build with pkg and run the binary on CentOS 7.7:

`./s2a: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./s2a)
./s2a: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./s2a)
./s2a: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./s2a)`

Seems to be an issue with 12.16.1?

**Comment by terryvdgriend** [comment]
@mkhurramali NodeJS upgraded there support regarding GCC (where this error originates from). since Node 12 it required GCC 6,3 or higher, which isn't installed on CentOS 7.x.

When I searched for this error I found this thread on another git repo:
https://github.com/cdr/code-server/issues/347#issuecomment-482670081

They have seem to solve it by copying it from another library which installs it and place it in the to be expected directory.

**Comment by mkhurramali** [comment]
Thank you @terryvdgriend. I will have a look at it. I did want to add additional information:

1. The current work around for me was to use `node12.13.1-linux-x64` as the target as opposed to `node12-linux-x64`.  So at least, it works with 12.13.1 on my CentOS server.

2. The CentOS server has node 13x installed also.

**Comment by awjreynolds** [comment]
@mkhurramali be aware that 12.13.1 has critical issues and should not be used in a public facing server environment.

**Comment by igorklopov** [comment]
@mkhurramali Can you please compile simple `console.log(process.versions)` application and run on your CentOS server. So that no `.node` modules are used (do you use them in production?). I suppose `CXXABI_1.3.9` is a requirement of some `.node` module, not of the packaged application.

**Comment by biancode** [comment]
The armv7 builds are missing in newer releases. It would be great to have it on each version, please. That makes it much easier and faster to compile well. ;)

**Comment by robertsLando** [comment]
https://github.com/robertsLando/pkg-binaries here you can find missing binaries

**Comment by hipstersmoothie** [comment]
@leerob This one can be close since the current release support 12.16.1
