### ISSUE TITLE
Old linux-x86 needed

### ISSUE THREAD

**Issue by mikakaraila** [vercel/pkg-fetch#86]
Cannot find this one anymore:
https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v8.16.2-linux-x86

I still need this for old linux-x86, any instructions or archive to access it?

Or has somebody still file in pkg-cache?

![image](https://user-images.githubusercontent.com/5184524/79534781-31565000-8084-11ea-9ee3-a7ef8c3b245f.png)

**Comment by jesec** [comment]
No. x86 32-bit is gone, and it is not going back. Switch to 64-bit.
