### ISSUE TITLE
pkg-fetch fails whenit tries to package an old clone node repository

### ISSUE THREAD

**Issue by tylez** [vercel/pkg-fetch#92]
I'm trying to package from node 10 a repository that use node 6 version but, when pkg clones node repository I got an ENOENT: no such file or directory error.

The case is that node 6 binary for windows is not present at https://github.com/zeit/pkg-fetch/releases/tag/v2.6 but yes for linux. So pkg clones node repository from github and when it tries to use these binaries it fails because it doesn't find the correct path.

![pkg error](https://user-images.githubusercontent.com/4256656/81291308-d5bb2900-9069-11ea-8c4a-2f0a054cc695.png)

Of course is not on the specified path:

![Captura de pantalla 2020-05-07 a las 14 07 23](https://user-images.githubusercontent.com/4256656/81292824-94784880-906c-11ea-875b-54e83be0d3ef.png)

**Comment by igorklopov** [comment]
What is the reason you need node 6?

**Comment by tylez** [comment]
due to an old project that we want to distribute without node dependency for out customers.

**Comment by hipstersmoothie** [comment]
@leerob I don't think we should be supporting super old node versions. This issue should be closed as "will not fix"
