### ISSUE TITLE
Add my FreeBSD build to assets

### ISSUE THREAD

**Issue by AHgPuK** [vercel/pkg-fetch#95]
Hi,

I've built updated version of pkg-fetch build for FreeBSD 12.16.1
Can you, please, add it to assets?
[fetched-v12.16.zip](https://github.com/vercel/pkg-fetch/files/4775976/fetched-v12.16.zip)

**Comment by Assfugil** [comment]
In the mean time, you can use this binary by adding it to `~/.pkg-fetch/v2.6` .

**Comment by hipstersmoothie** [comment]
@leerob this is a dupe of #39 and can be closed
