### ISSUE TITLE
doesn't work with ARMv8

### ISSUE THREAD

**Issue by jinweizhiyuan** [vercel/pkg-fetch#97]
My computer has an ARMv8 architecture
Nodejs version:node-v12.18.2-linux-arm64.tar.xz
The corresponding package could not be found？？？

**Comment by robertsLando** [comment]
@jinweizhiyuan You can find it here: https://github.com/robertsLando/pkg-binaries

**Comment by jinweizhiyuan** [comment]
@robertsLando Thank you.
